topic:
  tracab:
    name: tracabgen5_01_raw
    replication-factor: 2
    partitions: 3
  general-match:
    name: general_match
    replication-factor: 2
    partitions: 3
  general-match-phase:
    name: general_match_phase
    replication-factor: 2
    partitions: 3
  general-match-team:
    name: general_match_team
    replication-factor: 2
    partitions: 3
  general-match-player:
    name: general_match_player
    replication-factor: 2
    partitions: 3

file:
  raw:
    filepath: "./tracabGen5/133039.dat"
  metadata:
    filepath: "./tracabGen5/133039_metadata.json"

writer:
  tracab:
    gen5:
      time-start: 2022-12-02T20:00:00.000Z

spring:
  kafka:
    bootstrap-servers:
      - "${DATAPLATFORM_IP}:9092"
      - "${DATAPLATFORM_IP}:9093"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      retries: 1
      buffer-memory: 33554432
      properties:
        auto.register.schemas: true
        use.latest.version: true
    properties:
      schema.registry.url: "http://${DATAPLATFORM_IP}:8081"
