topic:
  tracab:
    name: tracabgen5_01_raw
    replication-factor: 2
    partitions: 3
  tracab-02:
    name: tracabgen5_02_filter
    replication-factor: 2
    partitions: 3
  tracab-03:
    name: tracabgen5_03_enriched
    replication-factor: 2
    partitions: 3
  general-01:
    name: general_01_player_ball
    replication-factor: 2
    partitions: 3
  general-02:
    name: general_02_team
    replication-factor: 2
    partitions: 3
  general-03:
    name: general_01_player_ball_compact
    replication-factor: 2
    partitions: 3
  general-acceleration:
    name: general_03_acceleration
    replication-factor: 2
    partitions: 3
  general-ball-zone-change:
    name: general_05_ball_zone_change
    replication-factor: 2
    partitions: 3
  general-ball-possession-change:
    name: general_04_ball_possession_change
    replication-factor: 2
    partitions: 3
  general-match:
    name: general_match
    replication-factor: 2
    partitions: 3
  general-match-phase:
    name: general_match_phase
    replication-factor: 2
    partitions: 3
  general-match-team:
    name: general_match_team
    replication-factor: 2
    partitions: 3
  general-match-player:
    name: general_match_player
    replication-factor: 2
    partitions: 3

file:
  raw:
    filepath: "./tracabGen5/20221206200000PORSUI/128075.dat"
  metadata:
    filepath: "./tracabGen5/20221206200000PORSUI/128075_metadata.json"

writer:
  tracab:
    gen5:
      time-start: 2022-12-06T20:00:00.000Z
  sleep-between-records: 0

spring:
  kafka:
    bootstrap-servers:
      - "${DATAPLATFORM_IP}:9092"
      - "${DATAPLATFORM_IP}:9093"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      retries: 1
      buffer-memory: 33554432
      properties:
        auto.register.schemas: true
        use.latest.version: true
    properties:
      schema.registry.url: "http://${DATAPLATFORM_IP}:8081"
